jobs:
  - template: default.yml@templates
    parameters:
      minrust: 1.40.0

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/v0.3
      endpoint: plainprogrammer
